version: "3"
services:
  www:
    build: .
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: myDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test

  adminer:
    image: adminer
    links:
      - db:db
    restart: always
    ports:
      - 8080:8080


